# Generated by Django 2.2.2 on 2019-07-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20190708_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img4',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
