# Generated by Django 2.2.2 on 2019-07-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20190708_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='basicPrice',
            field=models.IntegerField(),
        ),
    ]
