# Generated by Django 2.2.2 on 2019-07-08 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_product',
        ),
    ]
