# Generated by Django 2.2.2 on 2019-07-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_remove_cart_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_product',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to='MainApp.Product'),
        ),
    ]
